import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@mantine/core/styles.css";
import "./globals.css";
import {
  ColorSchemeScript,
  MantineProvider,
  mantineHtmlProps,
} from "@mantine/core";
import { NimbleServerHeader } from "./components/NimbleServerHeader/nimble-server-header";
import { DataProvider } from "./contexts/DataContext";

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" {...mantineHtmlProps}>
      <head>
        <ColorSchemeScript />
      </head>
      <body className={inter.className}>
        <MantineProvider
          theme={{
            fontFamily: inter.style.fontFamily,
            headings: { fontFamily: inter.style.fontFamily },
          }}
        >
          <DataProvider>
            <NimbleServerHeader />
            {children}
          </DataProvider>
        </MantineProvider>
      </body>
    </html>
  );
}
